import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class FlattenDirectoryForAI {

public static final String[] TEXT_FILE_EXTENSIONS = new String[] {
	  ".txt", ".java", ".md", ".log", ".xml", ".json", ".csv", ".html", ".css", ".js", ".properties", ".py", ".sh", ".c", ".cpp", ".h"
};

private static boolean CLI = false;

public static void main(String[] args) {
	Path selectedDirectory = null;
	int backtickCount = 5; // Default backtick count
	
	// Parse arguments
	if (args.length > 0) {
		CLI = true;
		selectedDirectory = Paths.get(args[0]);
		if (args.length > 1) {
			try {
				backtickCount = Integer.parseInt(args[1]);
			} catch (NumberFormatException e) {
				System.err.println("Warning: Invalid backtick count provided. Defaulting to 5.");
			}
		}
	} else {
		JFileChooser fc = new JFileChooser();
		fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
		fc.setDialogTitle("Select Directory to Flatten for AI");
		
		if (fc.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
			selectedDirectory = fc.getSelectedFile().toPath();
		} else {
			System.out.println("Operation cancelled.");
			return;
		}
	}
	
	if (selectedDirectory == null || !Files.isDirectory(selectedDirectory)) {
		System.err.println("Invalid directory selected.");
		return;
	}
	
	System.out.println("Scanning directory: " + selectedDirectory.toAbsolutePath());
	System.out.println("Using " + backtickCount + " backticks for code blocks.");
	processDirectory(selectedDirectory, backtickCount);
}

private static void processDirectory(Path rootDir, int backtickCount) {
	String fileTimestamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd_HH-mm"));
	Path outputPath = Paths.get(rootDir.toAbsolutePath().toString() + "_for_AI_" + fileTimestamp + ".md");
	
	try (BufferedWriter writer = new BufferedWriter(new FileWriter(outputPath.toFile()))) {
		// 1. Write Header
		DateTimeFormatter displayFormat = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
		String displayDate = LocalDateTime.now().format(displayFormat);
		
		writer.write("# AI Directory Export Utility\n");
		writer.write("> **Source Directory:** `" + rootDir.toAbsolutePath() + "`\n");
		writer.write("> **Export Date:** " + displayDate + "\n\n");
		
		writer.write(getFormattingRules(backtickCount));
		
		// 2. Write ASCII Directory Structure
		writer.write("## 1. Directory Structure\n\n");
		writer.write("```text\n");
		writer.write(generateDirectoryTree(rootDir.toFile()));
		writer.write("```\n\n");
			  
			  // 3. Write Flat File Contents
			  writer.write("## 2. File Contents\n\n");
		List<Path> textFiles = findTextFiles(rootDir);
		String backticks = generateBackticks(backtickCount);
		
		for (Path file : textFiles) {
			String relativePath = "#### File: " + rootDir.relativize(file).toString().replace("\\", "/");
			String extension = getFileExtension(file);
			
			writer.write(relativePath + "\n");
			writer.write(backticks + getMarkdownLanguage(extension) + "\n");
			
			try {
				List<String> lines = Files.readAllLines(file);
				for (String line : lines) {
					writer.write(line + "\n");
				}
			} catch (IOException e) {
				writer.write("// ERROR: Could not read file content: " + e.getMessage() + "\n");
			}
			
			writer.write(backticks + "\n\n");
		}
		
		System.out.println("Export complete! Saved to: " + outputPath.toAbsolutePath());
		if (!CLI && !java.awt.GraphicsEnvironment.isHeadless()) {
			JOptionPane.showMessageDialog(null, "Export Complete!\nSaved to:\n" + outputPath.toAbsolutePath());
		}
		
	} catch (IOException e) {
		System.err.println("Failed to write export file: " + e.getMessage());
		e.printStackTrace();
	}
}

// --- Utilities ---

private static String getFormattingRules(int backtickCount) {
	String backticks = generateBacktickRepresentative(backtickCount);
	StringBuilder rules = new StringBuilder();
	rules.append("## FORMATTING RULES & DEFINITIONS\n\n");
	rules.append("This document was generated by the **FlattenDirectoryForAI** utility.\n");
	rules.append("It stores the complete text-based contents of a project directory and its subpaths in a single file, optimized for Large Language Model ingestion without missing any contextual content.\n\n");
	rules.append("### Structure Breakdown:\n");
	rules.append("- **Directory Structure**: An ASCII tree representation of the entire folder tree, outlining the hierarchy of both text and non-text files.\n");
	rules.append("- **File Contents**: The raw text content of each identified text file.\n");
	rules.append("  - Each file block is prefixed strictly by its relative path followed by a colon (e.g., `#### File: src/main/Main.java:`).\n");
	rules.append("  - File content is completely enclosed within " + backtickCount + " backticks \"" + backticks + "\" (intentionally spaced for content integrity) to guarantee absolute safety against markdown collisions from the source code.\n");
	rules.append("  - Non-text files (binaries, images) are mapped in the Directory Structure but excluded from the flat text blocks to save context.\n");
	rules.append("---\n\n");
	return rules.toString();
}

private static String generateDirectoryTree(File root) {
	StringBuilder sb = new StringBuilder();
	sb.append(root.getName()).append("/\n");
	
	File[] files = root.listFiles();
	if (files != null) {
		sortFilesForTree(files);
		for (int i = 0; i < files.length; i++) {
			buildAsciiTree(files[i], "", i == files.length - 1, sb);
		}
	}
	return sb.toString();
}

private static void buildAsciiTree(File node, String prefix, boolean isLast, StringBuilder sb) {
	sb.append(prefix);
	if (isLast) {
		sb.append("└── ");
		prefix += "    ";
	} else {
		sb.append("├── ");
		prefix += "│   ";
	}
	
	sb.append(node.getName());
	if (node.isDirectory()) {
		sb.append("/");
	}
	sb.append("\n");
	
	if (node.isDirectory()) {
		File[] files = node.listFiles();
		if (files != null) {
			sortFilesForTree(files);
			for (int i = 0; i < files.length; i++) {
				buildAsciiTree(files[i], prefix, i == files.length - 1, sb);
			}
		}
	}
}

private static void sortFilesForTree(File[] files) {
	Arrays.sort(files, (a, b) -> {
		if (a.isDirectory() && !b.isDirectory()) return -1;
		if (!a.isDirectory() && b.isDirectory()) return 1;
		return a.getName().compareToIgnoreCase(b.getName());
	});
}

private static List<Path> findTextFiles(Path rootDir) throws IOException {
	try (Stream<Path> paths = Files.walk(rootDir)) {
		return paths
			  .filter(Files::isRegularFile)
			  .filter(FlattenDirectoryForAI::isTextFile)
			  .sorted() // Alphabetical sort for consistent output
			  .collect(Collectors.toList());
	}
}

private static boolean isTextFile(Path file) {
	String name = file.getFileName().toString().toLowerCase();
	for (String ext : TEXT_FILE_EXTENSIONS) {
		if (name.endsWith(ext)) {
			return true;
		}
	}
	return false;
}

private static String getFileExtension(Path file) {
	String name = file.getFileName().toString();
	int lastIndexOf = name.lastIndexOf(".");
	if (lastIndexOf == -1) {
		return "";
	}
	return name.substring(lastIndexOf + 1);
}

private static String getMarkdownLanguage(String extension) {
	switch (extension.toLowerCase()) {
		case "java": return "java";
		case "js": return "javascript";
		case "py": return "python";
		case "html": return "html";
		case "css": return "css";
		case "xml": return "xml";
		case "json": return "json";
		case "md": return "markdown";
		case "cpp": return "cpp";
		case "c": return "c";
		case "sh": return "bash";
		default: return "text";
	}
}

private static String generateBackticks(int count) {
	StringBuilder sb = new StringBuilder(count);
	for (int i = 0; i < count; i++) {
		sb.append("`");
	}
	return sb.toString();
}

private static String generateBacktickRepresentative(int count) {
	StringBuilder sb = new StringBuilder(count);
	for (int i = 0; i < count; i++) {
		sb.append("` ");
	}
	return sb.toString();
}

}
